slua-root = "Assets/Standard Assets/_Slua"
slua-editor-root = "Assets/Standard Assets/Editor"
slua-plugins-root = "Assets/Plugins"
slua-version = "Latest"

[ext-slua-plugins]
[[ext-slua-plugins.files]]
from = "Assets/Plugins"
to = "${slua-plugins-root}"
include = "**/*"

[ext-slua]
requires = [
    "ext-slua-plugins",
]
[[ext-slua.files]]
from = "Releases/${slua-version}"
to = "${slua-root}"
include = "SLua.*"

[ext-slua-src]
requires = [
    "ext-slua-plugins",
]
[[ext-slua-src.folders]]
from = "Assets/Slua/Script"
to = "${slua-root}/_Script"
[[ext-slua-src.folders]]
from = "Assets/Slua/Editor"
to = "${slua-editor-root}/_SluaEditor"
[[ext-slua-src.folders]]
from = "Assets/Slua/Doc"
to = "${slua-root}/_Doc"

